import { mock } from "bun:test";

/** Complete config mock factory. Must include ALL named exports from config.ts */
export function mockConfig(overrides: Record<string, unknown> = {}): void {
	mock.module("../src/config.js", () => ({
		config: {
			names: ["Luna", "Pixie"],
			keywords: ["hello", "hi", "hey", "help", "question", "ai", "llm", "bot"],
			randomChance: 0.015,
			cooldownSeconds: 8,
			replyInDM: true,
			concentration: {
				mention: { delay_min: 300, delay_max: 1500, ignore_chance: 0, reaction_chance: 0.08 },
				dm: { delay_min: 400, delay_max: 1800, ignore_chance: 0, reaction_chance: 0.05 },
				name: { delay_min: 800, delay_max: 4000, ignore_chance: 0.05, reaction_chance: 0.06 },
				keyword: { delay_min: 1000, delay_max: 3500, ignore_chance: 0.08, reaction_chance: 0.04 },
				"follow-up": { delay_min: 500, delay_max: 2000, ignore_chance: 0, reaction_chance: 0.03 },
				random: { delay_min: 1500, delay_max: 5000, ignore_chance: 0.15, reaction_chance: 0.02 },
				default: { delay_min: 800, delay_max: 4000, ignore_chance: 0.08, reaction_chance: 0.06 },
			},
			serverEmojiChance: 0.3,
			reactions: ["👀", "😄", "🤔", "👋", "🔥"],
			spontaneousIntervalMs: 300_000,
			spontaneousChance: 0.12,
			spontaneousContextMessages: 5,
			spontaneousWhitelist: "*",
			typoChance: 0.06,
			typoLayout: "azerty",
			typoCorrectionDelay: 2000,
			typoCorrectionDelayMax: 4000,
			typoCorrectionStyle: "mixed",
			typingWpm: 300,
			hesitationChance: 0.15,
			hesitationWords: ["uh...", "um...", "well...", "i mean...", "hmm...", "so..."],
			forgetChance: 0.03,
			inactivityWarmupMinutes: 10,
			inactivityWarmupMultiplier: 2,
			voiceMessageChance: 0.08,
			sleepSchedule: { enabled: false, start: "23:00", end: "08:00", timezone: "Europe/Paris", behavior: "sleep" },
			dynamicStatus: [] as { status: string; text: string; type: number }[],
			dynamicStatusIntervalMinutes: 15,
			replyStyles: [
				{ message_reference: true, mention_replied_user: false, weight: 50 },
				{ message_reference: true, mention_replied_user: true, weight: 15 },
				{ message_reference: false, mention_replied_user: false, weight: 30 },
				{ message_reference: false, mention_replied_user: true, weight: 5 },
			],
			...overrides,
		} as Record<string, unknown>,
		ffmpegPath: "/usr/bin/ffmpeg",
		ffprobePath: "/usr/bin/ffprobe",
		DISCORD_TOKEN: "mock_token",
		LLAMA_CLI_PATH: "llama/llama-cli",
		LLAMA_MODEL_PATH: "models/model.gguf",
		LLM_HOST: "localhost",
		LLM_PORT: 3124,
		LLM_MODE: "proxy",
		SYSTEM_PROMPT: "You are a test bot",
		jinjaTemplate: "template",
		ttsModelPath: "tts/model.onnx",
		ttsBinaryPath: "bin/piper",
		llamaArgs: [] as string[],
		setLLMMode() {},
		watchConfig() {},
		pickReplyStyle() { return { messageReference: true, mentionRepliedUser: false }; },
	}));
}
