%%{init: {"theme":"dark"}}%%
gantt
    title Sleep schedules
    dateFormat HH:mm
    axisFormat %H:%M
    tickInterval 2hour

    section Behavior
    Awake        : active, 07:00, 3h
    Short        : short, 10:00, 1h
    Awake        : active2, 11:00, 5h
    Slow         : slow, 16:00, 2h
    Awake        : active3, 18:00, 4h
    Sleep        : sleep, 22:00, 9h
