%%{init: {"theme":"dark"}}%%
xychart-beta
  title "Distribution of turns per exchange"
  x-axis ["2", "3", "4", "5", "6", "7+"]
  y-axis "Exchanges (millions)" 0 --> 6
  bar [5.80, 1.04, 0.30, 0.10, 0.04, 0.04]
